### PR TITLE
Removes the power status if the only power source is AC

### PR DESCRIPTION
**Pull request by gingeralesy**
I was getting annoyed by the status bar message that kept telling me there's no info on AC power.

### CODE REVIEW

**Comment by Shinmera** [comment]
Is this on a laptop or on a workstation? If the former, then that's suspicious because it should tell you current charging status. If it's the later then that's also suspicious because workstations should not have a power supply listed.

**Comment by gingeralesy** [comment]
That's exactly why it checks if the dir only has one sub-directory. Wouldn't laptop have both AC and Battery there?

**Comment by Shinmera** [comment]
The module that's responsible for actually fetching the battery information does something that I don't know about. All I want to do with that check there is see whether it's a laptop at all or not, as on a workstation that information would be useless. On all of my laptops, it properly notices when it is plugged in and changes the display information accordingly. On all of my workstations, it doesn't display it at all as the directory is empty.

**Comment by gingeralesy** [comment]
Ah, I use it on a virtual machine running on a desktop host. And the AC folder appears there. And it's quite the bother to me.

**Comment by Shinmera** [comment]
Ok, but then you should check whether `/sys/class/power_supply` contains any batteries at all, not just whether the first one is a power supply.

**Comment by gingeralesy** [comment]
I checks that the length of the array is exactly 1 and if the only item there is "AC". That way there can not be battery power supply.

Oh, there's an issue. There should be 0 < len(array), not 1 < len(array).

**Comment by Shinmera** [comment]
I know, I read your patch. It's not a good solution though. You should loop through the directories and check whether any of them are a battery device.

**Comment by Shinmera** [comment]
The type will say "Battery".

**Comment by gingeralesy** [comment]
There you go. Checks all power sources for a battery.

**Pull request merged**
